---
- name: Instalar paquetes base del aula en Windows
  ansible.windows.win_shell: |
    winget install --id {{ item }} -e --source winget --accept-source-agreements --accept-package-agreements --disable-interactivity
  loop: "{{ paquetes_base }}"

- name: Instalar paquetes extra en Windows
  ansible.windows.win_shell: |
    winget install --id {{ item }} -e --source winget --accept-source-agreements --accept-package-agreements --disable-interactivity
  loop: "{{ paquetes_extra }}"
  when: paquetes_extra is defined
