---
- name: Configurar Aula 2
  hosts: aula2
  become: true
  vars_files:
    - ../vars/usuarios_aula2.yml
    - ../vars/paquetes_comunes.yml
  roles:
    - paquetes
    - usuarios
    - seguridad
    - configuracion
